### ISSUE TITLE
Implementar carga de un catálogo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#3]
- [x] Cargar un archivo de catálogo (#7)
 - [x] Validación de catálogo al momento de carga (#8)
 - [x] Devolver links de descarga (#10)
 - [x] Descargar un archivo de catálogo a través de URL (#11)
 - [x] Versionar un catálogo (#9)

-------------

Un usuario puede cargar un catálogo por primera vez o pisar uno existente, siempre que:

+ Esté asociado al catálogo que desea cargar

Los inputs pueden ser:

+ Catálogo XLSX (archivo)
+ Catálogo XLSX (URL desde donde descargarlo)
+ Catálogo JSON (archivo)
+ Catálogo JSON (URL desde donde descargarlo)

Cargar un catálogo desata las siguientes acciones:

+ Valida el catálogo e informa los errores encontrados por UI (el error donde no existe "distribution_downloadURL" debe ser tratado aparte y no mostrado en la UI como un error, sino como información de que esa distribución todavía no ha sido cargada en la infraestructura o debe especificarse una URL en su lugar). La validación *no tiene consecuencias, más que informativas para el usuario*.

+ Crea internamente las carpetas que fueran necesarias para cargar el catálogo por primera vez (si es el caso).

+ Crea copias *del catálogo existente previamente, si lo hay* con la fecha del día de hoy según el siguiente formato: `https://infra.datos.gob.ar/catalog/{catalog_id}/data-20190801.json` y `https://infra.datos.gob.ar/catalog/{catalog_id}/catalog-20190801.xlsx`.

+ Crea o pisa las copias permanentes del catálogo que están en `https://infra.datos.gob.ar/catalog/{catalog_id}/data.json` y en `https://infra.datos.gob.ar/catalog/{catalog_id}/catalog.xlsx`.

+ Devuelve por UI al usuario los 2 links de descarga generados para el catálogo permanente y, en sección aparte, todos los links de descarga disponibles de versiones anteriores (del más reciente al más antiguo).

Notas:

+ Los catálogos en XLSX pueden tener columnas adicionales útiles para los usuarios, formato adicional, estilos, etc. En ningún momento debe usarse la función "to_xlsx()" si el catálogo de origen es un XLSX porque se distorsionaría el catálogo XLSX original. Debe preservarse el original, salvo que el usuario haya cargado un JSON. En este último caso sí debe usarse un "to_xlsx()" para crear la versión en XLSX.
